---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=wp-nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template: src=wp-nginx.conf-d.conf dest=/etc/nginx/conf.d/wp.conf

- name: insert firewalld rule for nginx
  firewalld: port={{ nginx_port }}/tcp permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: http service state
  service: name=nginx state=started enabled=yes
